name: Deploy to VPS

on:
  push:
    branches:
      - main  # Or your specific branch like 'development'

jobs:
  build:
    runs-on: windows-latest  # You can choose a different runner if you prefer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Install dependencies
        run: |
          choco install nuget.commandline

      - name: Build the solution
        run: |
          msbuild C:\Users\Sharkawy\aspnet-core\ExpressMs.sln /p:Configuration=Release

      - name: Publish the code
        run: |
          msbuild C:\Users\Sharkawy\aspnet-core\ExpressMs.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Copy files to VPS
        run: |
          $password = ConvertTo-SecureString "Express1$$" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("100-233-109-208\express", Express1$$)
          Copy-Item -Path "C:\Users\Sharkawy\Dropbox\My PC (DESKTOP-AG3QV3I)\Desktop\ExpressPublic" -Destination "\\200.109.233.100\C:\inetpub\Backend\Publish" -Recurse -Credential $credential
